# config_cpu.yaml
workerPoolSpecs:
  - machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: 'europe-west1-docker.pkg.dev/cds-predictor/cds-repo/train:latest'
        env:
        - name: WANDB_MODE
          value: offline
