program: src/cds_repository/train.py
project: cds_predictor

method: bayes

command:
  - ${env}
  - python
  - ${program}
  - lr=${lr}
  - dropout=${dropout}
  - weight_decay=${weight_decay}
  - scheduler_factor=${scheduler_factor}
  - channels=${channels}

metric:
  name: loss/val
  goal: minimize

parameters:
  lr:
    distribution: log_uniform_values
    min: 1.0e-5
    max: 1.0e-2

  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5

  weight_decay:
    distribution: log_uniform_values
    min: 1.0e-4
    max: 1.0e-1

  channels:
    values:
      - [32, 64, 128]
      - [64, 128, 256]
      - [128, 256, 512]
      - [64, 128, 256, 512]

  epochs:
    values: [20, 30, 40]

  scheduler_factor:
    distribution: uniform
    min: 0.1
    max: 0.9

early_terminate:
  type: hyperband
  min_iter: 5
